name: Deploy Application

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build project
        run: mvn clean install -DskipTests
      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t santo32/agenda .
      - name: Push image docker
        run: docker push santo32/agenda

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Remove docker container
        run: docker rm -f agenda
      - name: Pull image from docker hub
        run: docker pull santo32/agenda:latest
      - name: Remove docker container
        run: docker run -d -p 2027:2027 --name agenda santo32/agenda
